apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-consumer
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      containers:
        - name: app
          image: notificationpoc.azurecr.io/notification-consumer:latest
          ports:
            - containerPort: 8082
          imagePullPolicy: Always